apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: mobydock
  name: mobydock
  namespace: mobydock
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mobydock
    spec:
      containers:
      - args:
        - gunicorn
        - -b
        - 0.0.0.0:8000
        - --reload
        - --access-logfile
        - '-'
        - mobydock.app:create_app()
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        image: preinking/mobydock
        name: mobydock
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /mobydock
          name: mobydock-data
      restartPolicy: Always
      volumes:
      - name: mobydock-data
        emptyDir: {}
status: {}
