apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    flux.weave.works/automated: "true"
  creationTimestamp: null
  generation: 1
  labels:
    app: mobydock-demo
    template: mobydock-demo-template
  name: mobydock
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mobydock
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mobydock
    spec:
      containers:
      - args:
        - gunicorn
        - -b
        - 0.0.0.0:8000
        - --reload
        - --access-logfile
        - '-'
        - mobydock.app:create_app()
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        image: preinking/mobydock:1.2.0
        imagePullPolicy: Always
        name: mobydock
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
