apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: mobydock
  name: mobydock
  namespace: mobydock
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mobydock
    spec:
      containers:
      - env:
        - name: PYTHONUNBUFFERED
          value: "true"
        image: preinking/mobydock
        name: mobydock
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
