apiVersion: v1
data:
  database-name: bW9ieWRvY2s=
  database-password: eW91cnBhc3N3b3Jk
  database-user: bW9ieWRvY2s=
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    app: postgresql-persistent
    template: postgresql-persistent-template
  name: postgresql
  namespace: mobydock
type: Opaque
