apiVersion: v1
data:
  database-password: eW91cnBhc3N3b3Jk
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  creationTimestamp: null
  labels:
    app: redis-ephemeral
    template: redis-ephemeral-template
  name: redis
  namespace: mobydock
type: Opaque
